# Generated by Django 3.2.13 on 2022-04-13 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicequestion',
            name='answer',
        ),
        migrations.AddField(
            model_name='choicequestion',
            name='answer',
            field=models.ManyToManyField(to='questions.ChoiceAnswer'),
        ),
        migrations.RemoveField(
            model_name='choicequestion',
            name='user',
        ),
        migrations.AddField(
            model_name='choicequestion',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='valuequestion',
            name='user',
        ),
        migrations.AddField(
            model_name='valuequestion',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
