# Generated by Django 3.2.13 on 2022-04-13 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0002_auto_20220413_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicequestion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='valuequestion',
            name='user',
        ),
        migrations.AddField(
            model_name='choiceanswer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choicequestion',
            name='section',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='valueanswer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='valuequestion',
            name='section',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
