# Generated by Django 3.2.13 on 2022-04-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_sectionquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choiceanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='choicequestion',
            name='section',
        ),
        migrations.RemoveField(
            model_name='valueanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='valuequestion',
            name='section',
        ),
        migrations.RemoveField(
            model_name='sectionquestions',
            name='questions',
        ),
        migrations.AddField(
            model_name='sectionquestions',
            name='questions',
            field=models.ManyToManyField(to='questions.ChoiceQuestion'),
        ),
    ]
